var color = ["red"];
var color3 = ["red", "blue", ["yellow", "grey"]];
var color4 = color.concat("blue", ["red", "blue", ["yellow", "grey"]]);
var color5 = color.concat("blue", [["red", "blue", ["yellow", "grey"]]]);
var color6 = color.concat("blue", color3);
var color7 = color.concat("blue", [color3]);
console.log(color3);
console.log(color4);
console.log(color5);
console.log(color6);
console.log(color7);
console.log(color3.toString());